# Generated by Django 4.2.2 on 2023-07-07 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_users'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='tier',
            field=models.IntegerField(default=0),
        ),
    ]
