# Generated by Django 4.1.5 on 2023-07-17 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_users_tier'),
    ]

    operations = [
        migrations.AddField(
            model_name='mailinglist',
            name='link_token',
            field=models.CharField(default='', max_length=8),
        ),
        migrations.AddField(
            model_name='users',
            name='link_token',
            field=models.CharField(default='', max_length=8),
        ),
    ]
