# Generated by Django 4.1.5 on 2023-07-27 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_mailinglist_link_token_users_link_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mailinglist',
            name='link_token',
            field=models.CharField(default='nSbDJn', max_length=8),
        ),
        migrations.AlterField(
            model_name='users',
            name='link_token',
            field=models.CharField(default='vpjaEy', max_length=8),
        ),
    ]
